version: "3.9"
services:

# === Private Cloud Services ===
  cloudflare-ddns:
    image: hotio/cloudflare-ddns:stable-3360b95-196-linux-amd64
  openvpn-as:
    image: linuxserver/openvpn-as
  pihole: 
    image: pihole/pihole:latest
  traefik:
    image: traefik:v1.7
  portainer:
    image: portainer/portainer
  unifi-controller:
    image: linuxserver/unifi-controller:LTS
  unms:
    image: nico640/docker-unms

# === Monitoring ===
  grafana:
    image: grafana/grafana
  hddtemp:
    image: drewster727/hddtemp-docker
  hs110:
    image: wouterstemgee/hs110influx:latest
  influx:
    image: influxdb:latest
  telegraf:
    image: telegraf:alpine

# === Home Media Streaming ===
  plex:
    image: linuxserver/plex
    devices:
      - "/dev/dri:/dev/dri" # Intel QuickSync passthrough (iGPU transcoding)
    environment:
      - UMASK_SET="022"
      - PLEX_CLAIM="" # Plex Pass
    ports:
      - "32400:32400" # WebUI
      - "3005:3005" # Plex Companion
      - "8324:8324" # Roku
      - "32469:32469" # DLNA Server
      - "1900:1900" # DLNA Server
      - "32410:32410" # GDM - Plex autodiscovery protocol (G'Day Mate)
      - "32412:32412" # GDM
      - "32413:32413" # GDM
      - "32414:32414" # GDM
    volumes:
      - plex-config-volume:/config
      - plex-driver-volume:/usr/lib/plexmediaserver/lib/dri # force fixed driver (Intel UHD Graphics 605)

  tautulli:
    image: linuxserver/tautulli
  ombi:
    image: linuxserver/ombi
  transmission:
    image: linuxserver/transmission
  sonarr:
    image: linuxserver/sonarr
  radarr:
    image: linuxserver/radarr
  jackett:
    image: linuxserver/jackett
  flaresolverr:
    image: flaresolverr/flaresolverr

# === Home Automation ===
  home-assistant:
    image: homeassistant/home-assistant
    environment:
      - TZ="Europe/Brussels"
    ports:
      - "8123:8123"
    volumes:
      - home-assistant-volume:/config

# === Game Servers ===
  factorio:
    image: factoriotools/factorio:stable
    restart: unless-stopped
    ports:
      - "34197:34197"
    volumes:
      - factorio-volume:/factorio
    
  minecraft:
    image: ich777/minecraftbasicserver
    restart: unless-stopped
    environment:
      - JAR_NAME="spigot"
      - XMS_SIZE="1024"
      - XMX_SIZE="4096"
      - GAME_PARAMS=""
      - ACCEPT_EULA="true"
      - RUNTIME_NAME="basicjre"
    ports:
      - "25565:25565"
      - "8123:8123" # dynmap
    volumes:
      - minecraft-server-volume:/serverdata/serverfiles
  
  discord-event-bot:
    image: wouterstemgee/discord-event-bot:latest
    restart: unless-stopped
    environment:
      - TOKEN=""
      - DATABASE_URI="mongodb://discord-bot-db:27017/"
      - EVENT_CHANNEL_ID=""
    networks:
      - discord-bot-network
    depends_on:
      - discord-event-bot-db
  
  discord-event-bot-db:
    image: mongo:4.4.4
    volumes:
      - discord-bot-db-volume:/data/db

volumes:
  plex-config-volume:
  plex-driver-volume:
  home-assistant-volume:
  factorio-volume:
  minecraft-server-volume:
  discord-bot-db-volume:   

networks:
  discord-bot-network:
  testing-network:
