apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cattle-system-cert
  namespace: cattle-system
spec:
  commonName: rancher.wouterstemgee.be
  secretName: rancher-wouterstemgee-be-cert
  dnsNames:
    - rancher.wouterstemgee.be
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
